#!/bin/bash
echo "Enter your password"
read password
len=${#password}
if test $len -ge 8 
then
echo "$password" | grep -q '[0-9]'
if test $? -eq 0
then
echo "$password" | grep -q '[A-Z]'
if test $? -eq 0 
then
echo "$password" | grep -q '[a-z]'
if test $? -eq 0 
then
echo "Strong password"
else
echo "weak password should include a lowercase"
fi
else
echo "weak password should include a capitalcase"
fi
else
echo "weak password should include a number"
fi
else
echo "weak password should have atleast 8 character"
fi
